// Generated by models/HarpoonCannon/prepare_materials.py. Authored data only.
#pragma once
#include "CoreMinimal.h"

namespace HarpoonPaletteData
{
struct FSlot { const TCHAR* Name; FLinearColor BaseColor; float Roughness; float Metallic; FLinearColor Emissive; };
inline const FSlot Slots[] = {
    {TEXT("CopperCoil"), FLinearColor(0.361867191f, 0.047366143f, 0.002878828f, 1.0f), 0.400000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("DarkMetal"), FLinearColor(0.017744508f, 0.024421807f, 0.027420549f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("EdgeMetal"), FLinearColor(0.081532349f, 0.099300103f, 0.105649027f, 1.0f), 0.400000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("MachinedSteel"), FLinearColor(0.156181864f, 0.189939499f, 0.198943943f, 1.0f), 0.400000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("PowerBlue"), FLinearColor(0.000182922f, 0.301676573f, 0.681419299f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000073169f, 0.120670629f, 0.272567720f, 1.0f)},
    {TEXT("RailBlue"), FLinearColor(0.006309573f, 0.017744508f, 0.025897505f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("RubberCable"), FLinearColor(0.007781510f, 0.011237647f, 0.012210524f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("SafetyOrange"), FLinearColor(0.646234999f, 0.047366143f, 0.000626541f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
    {TEXT("ServicePanel"), FLinearColor(0.198943943f, 0.217637641f, 0.198943943f, 1.0f), 0.650000000f, 0.000000000f, FLinearColor(0.000000000f, 0.000000000f, 0.000000000f, 1.0f)},
};
}
