"""Reproduce preview colors as model-owned, UV-free Unreal material inputs."""
import argparse
import hashlib
import json
import math

from build_model import SOURCE_DIR, read_obj

SHINY_SLOTS={'MachinedSteel','EdgeMetal','CopperCoil'}


def palette():
    descriptor=json.loads((SOURCE_DIR/'runtime-model.json').read_text())
    for source in descriptor['sources'].values():
        path=SOURCE_DIR/source['path']
        if hashlib.sha256(path.read_bytes()).hexdigest().upper()!=source['sha256']:
            raise ValueError('Model source hash mismatch: '+str(path))
    mtl=descriptor['sources']['mtl']
    colors={}
    name=None
    for line in (SOURCE_DIR/mtl['path']).read_text().splitlines():
        fields=line.split()
        if fields and fields[0]=='newmtl':
            name=fields[1]
        elif fields and fields[0]=='Kd':
            rgb=[float(v) for v in fields[1:]]
            if name is None or name in colors or len(rgb)!=3 or not all(
                    math.isfinite(v) and 0<=v<=1 for v in rgb):
                raise ValueError('Invalid/duplicate MTL color: '+str(name))
            colors[name]=rgb
    scene=read_obj(SOURCE_DIR/descriptor['sources']['obj']['path'])
    slots=[]
    for name in sorted({o.material for o in scene.objects}):
        rgb=colors[name]
        # The authored preview renderer uses power 2.2, not Unreal's sRGB byte
        # conversion. Store linear floats explicitly; do not gamma-decode again.
        linear=[round(v**2.2,9) for v in rgb]
        slots.append({'name':name,'baseColorLinear':linear,
                      'roughness':0.4 if name in SHINY_SLOTS else 0.65,
                      'metallic':0.0,
                      'emissiveColorLinear':[round(v*0.4,9) for v in linear]
                          if name=='PowerBlue' else [0.0,0.0,0.0]})
    return {'schemaVersion':1,'sourceMtl':mtl,
            'colorContract':'Preview Kd raised to power 2.2; linear shader inputs; opaque default-lit, single-sided',
            'slots':slots}


def header(data):
    def number(v):
        return f'{float(v):.9f}f'
    def color(rgb):
        return 'FLinearColor('+', '.join(number(v) for v in rgb)+', 1.0f)'
    lines=['// Generated by models/HarpoonCannon/prepare_materials.py. Authored data only.',
           '#pragma once','#include "CoreMinimal.h"','',
           'namespace HarpoonPaletteData','{',
           'struct FSlot { const TCHAR* Name; FLinearColor BaseColor; float Roughness; float Metallic; FLinearColor Emissive; };',
           'inline const FSlot Slots[] = {']
    for slot in data['slots']:
        lines.append('    {TEXT("'+slot['name']+'"), '+color(slot['baseColorLinear'])+', '+
                     number(slot['roughness'])+', '+number(slot['metallic'])+', '+
                     color(slot['emissiveColorLinear'])+'},')
    lines+=['};','}']
    return '\n'.join(lines)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true',help='Regenerate model-owned palette outputs')
    args=parser.parse_args()
    data=palette()
    outputs={SOURCE_DIR/'material-palette.json':json.dumps(data,indent=2)+'\n',
             SOURCE_DIR/'Unreal'/'HarpoonPaletteData.h':header(data)}
    for path,content in outputs.items():
        if args.write:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_bytes(content.encode('utf-8'))
        elif not path.exists() or path.read_text(encoding='utf-8')!=content:
            raise ValueError('Palette output missing/stale: '+str(path))
    print(json.dumps({'result':'passed','slots':[s['name'] for s in data['slots']],
                      'palette':str(SOURCE_DIR/'material-palette.json'),
                      'shaderValidation':'pending Unreal compile/cook and runtime',
                      'runtimeDescriptorChanged':False}))


if __name__=='__main__': main()
