# Installed beside the mod containers in Voyage/Content/Paks/GyroKeyboardControl.ini.
# Restart Voyage after editing. Decimal point only; NO INLINE COMMENTS!

# Defines how fast the pitch changes from 0 to max when W/S are hold. Seconds.
PitchRampSeconds=3.0

# AVOID CHANGING SETTINGS BELOW UNLESS YOU KNOW WHAT YOU'RE DOING!
# cm/s^2
AltitudeStabilizationVerticalDeceleration=100.0
# cm/s^2
HorizontalVelocityDecayAcceleration=150.0
# Rotor rotation velocity in internal units. 30% of throttle is ~1176 units or ~1348 degrees/second.
StabilizationMinimumPropellerVelocity=390.0
