# Installed beside the mod containers in Voyage/Content/Paks/GyroKeyboardControl.ini.
# Restart Voyage after editing. Decimal point only; NO INLINE COMMENTS!
PitchRampSeconds=3.0

# AVOID CHANGING SETTINGS BELOW UNLESS YOU KNOW WHAT YOU'RE DOING!
# cm/s
AltitudeStabilizationVerticalDeceleration=100.0
# cm/s^2
HorizontalVelocityDecayAcceleration=150.0
